name: Cleanup Docker Hub Tags

on:
  workflow_dispatch:  # 수동 실행

env:
  DOCKER_IMAGE: kman0001/tubesync-plex

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq and python3
        run: sudo apt-get update && sudo apt-get install -y jq python3 curl

      - name: Authenticate to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: List and delete old tags safely
        run: |
          REPO=${{ env.DOCKER_IMAGE }}
          USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          TOKEN=${{ secrets.DOCKERHUB_TOKEN }}

          # 페이지네이션 처리
          URL="https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=100"
          while [ -n "$URL" ]; do
            RESPONSE=$(curl -s -u $USERNAME:$TOKEN "$URL")
            TAGS=$(echo "$RESPONSE" | jq -r '.results[].name')

            for TAG in $TAGS; do
              if [[ "$TAG" != "latest" && "$TAG" != "latest-amd64" && "$TAG" != "latest-arm64" ]]; then
                # URL 인코딩
                TAG_ENCODED=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$TAG'''))")
                echo "Deleting tag: $TAG"
                curl -s -X DELETE -u $USERNAME:$TOKEN "https://hub.docker.com/v2/repositories/$REPO/tags/$TAG_ENCODED/"
              fi
            done

            # 다음 페이지 URL
            URL=$(echo "$RESPONSE" | jq -r '.next')
          done
