name: Docker Hub Keep Alive

on:
  schedule:
    - cron: '0 0 1 * *'   # 매달 1일 00:00 UTC (한국시간 오전 9시)
  workflow_dispatch:        # 수동 실행도 허용

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull and re-push image
        run: |
          IMAGE="kman0001/tubesync-plex:latest"
          echo "Pulling $IMAGE..."
          docker pull $IMAGE || (echo "Image not found, skipping" && exit 0)

          echo "Re-pushing $IMAGE..."
          docker push $IMAGE

          echo "✅ Keep-alive push completed for $IMAGE"
