name: Build and Push Multi-Arch Docker Image

on:
  schedule:
    - cron: '0 0 1 * *'  # 1개월마다 1일 00:00 UTC
  workflow_dispatch:   # ✅ 수동 실행만 허용
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - '.github/workflows/**'

env:
  DOCKER_IMAGE: kman0001/tubesync-plex

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. 멀티아키 이미지 빌드 및 푸시
      - name: Build & push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:latest-amd64
            ${{ env.DOCKER_IMAGE }}:latest-arm64
